### ISSUE TITLE
A faster dob

### ISSUE THREAD

**Issue by gnpe-nuuk** [anhoej/cprr#3]
As a user of R, I have needed to calculate the date of birth from a CPR number. I found your package, which I have been happy to use. I have rewritten your "dob" function to make it run faster, as I have a very large dataset. See below.

dob1 <- function(pnr) {
  #use package dplyr
  dd <- substr(pnr, 1, 2)
  mm <- substr(pnr, 3, 4)
  yy_txt <- substr(pnr, 5, 6)
  yy <- as.numeric(yy_txt)
  x7 <- substr(pnr, 7, 7)
  #calculates first 2 digit af year
  yy100 = dplyr::case_when(
    x7 %in% c("0", "1", "2", "3") ~ "19",
    x7 %in% c("4", "9") ~ dplyr::if_else(yy<37, "20", "19"),
    x7 %in% c("5", "6", "7", "8") ~ dplyr::if_else(yy<58, "20", "18"),
    .default = NA
  )
  #date as text
  dob <- dplyr::if_else(is.na(x7), NA, paste(paste0(yy100,yy_txt), mm, dd, sep = "-"))
  # output
  return(as.Date(dob))
}

**Comment by anhoej** [comment]
Thanks alot. Could you make the function independent of external packages (dplyr)? I strive to keep my packages as free of external dependencies as possible.

**Comment by gnpe-nuuk** [comment]
Now with "ifelse" from base:

dob1_base <- function(pnr) {
  dd <- substr(pnr, 1, 2)
  mm <- substr(pnr, 3, 4)
  yy_txt <- substr(pnr, 5, 6)
  yy <- as.numeric(yy_txt)
  x7 <- substr(pnr, 7, 7)
  
  #Replace case_when with nested ifelse logic
  yy100 <- ifelse(x7 %in% c("0", "1", "2", "3"), "19",
                  ifelse(x7 %in% c("4", "9"),
                         ifelse(yy < 37, "20", "19"),
                         ifelse(x7 %in% c("5", "6", "7", "8"),
                                ifelse(yy < 58, "20", "18"), 
                                NA)))
  
  #Replace if_else with ifelse
  dob <- ifelse(is.na(x7), 
                NA,
                paste0(yy100, yy_txt, "-", mm, "-", dd))
  
  return(dob)
}

**Comment by anhoej** [comment]
Great, thanx. Will consider your suggestion for the next update.
